/**
 * How Might We (HMW) statements per theme for design discussions.
 * Key format: "category|subCategory|themeId".
 * Generated by: npm run generate-hmw
 */

export type HmwStatementsMap = Record<string, string>;

export const HMW_STATEMENTS: HmwStatementsMap = {
  "Attendance & Registers|Bulk edit and workflow|friction": "How might we streamline bulk attendance workflows for attendance officers so that they can update large groups of pupils in just a few clear steps without getting lost in filters?",
  "Attendance & Registers|Bulk edit and workflow|peripatetic": "How might we make it effortless for office staff to record peripatetic and external staff attendance so that they can move away from paper registers and keep everything in one reliable place?",
  "Attendance & Registers|Bulk edit and workflow|latecomer": "How might we support pastoral and attendance teams in tracking latecomers so that they can quickly spot patterns in late marks and intervene earlier with pupils who need help?",
  "Attendance & Registers|Pre-planned absence and notes|notes-flow": "How might we connect pre-planned absence notes to lesson registers for classroom teachers so that they can instantly see the reason a pupil is away at the moment of taking the register?",
  "Attendance & Registers|Pre-planned absence and notes|overridden": "How might we protect pre-set marks for attendance officers so that they can trust planned absences will not be accidentally overwritten when teachers complete registers?",
  "Attendance & Registers|Pre-planned absence and notes|fines": "How might we help school admins manage fines and unauthorised absence rules so that they can confidently apply thresholds without constant manual calculations?",
  "Attendance & Registers|Pre-planned absence and notes|ad-hoc": "How might we make it simple for staff to record ad hoc interventions as absences so that they can reflect in-school support accurately without fighting the system?",
  "Attendance & Registers|Codes and marks|locking": "How might we give schools fine-grained control over who can change marks so that attendance teams can keep data accurate while still letting teachers correct genuine mistakes?",
  "Attendance & Registers|Codes and marks|custom-census": "How might we simplify custom attendance codes and census mapping for data managers so that they can meet statutory requirements without maintaining complex side spreadsheets?",
  "Attendance & Registers|Codes and marks|suspended": "How might we make suspended or incomplete registers easy to spot and resolve for attendance officers so that they can close gaps quickly and keep daily figures trustworthy?",
  "Attendance & Registers|Clubs and wrap-around|capacity": "How might we help staff manage club capacity and bookings so that they can confidently see who is attending and avoid overbooking or missed places?",
  "Attendance & Registers|Clubs and wrap-around|cancel": "How might we make cancelling club sessions straightforward for office staff so that they can notify families quickly when sessions are called off or rescheduled?",
  "Attendance & Registers|Clubs and wrap-around|reporting": "How might we improve club reporting for leaders so that they can easily review attendance over time and adjust provision to match demand?",
  "Attendance & Registers|Evacuation and emergency registers|access": "How might we surface evacuation registers in one obvious place for all staff so that they can reach the right list instantly in an emergency?",
  "Attendance & Registers|Evacuation and emergency registers|format": "How might we offer flexible evacuation list formats for school leaders so that they can print or export the view that best matches their on-site procedures?",
  "Attendance & Registers|Evacuation and emergency registers|display": "How might we design evacuation registers for maximum legibility so that staff can quickly confirm who is present, even in stressful conditions or poor visibility?",
  "Attendance & Registers|Reporting and statistics|meal": "How might we connect attendance and meal data for kitchen teams so that they can prepare the right number of meals without chasing last‑minute updates?",
  "Attendance & Registers|Reporting and statistics|persistent": "How might we surface persistent absence patterns for attendance teams so that they can prioritise support for the pupils and families who most need it?",
  "Attendance & Registers|Reporting and statistics|percentage": "How might we show key attendance percentages in context for school leaders so that they can understand trends by date, group, and threshold at a glance?",
  "Attendance & Registers|Staff absence and cover|udf": "How might we bring useful student context, like reading age, into registers for teachers so that they can tailor support without jumping between multiple screens?",
  "Attendance & Registers|Staff absence and cover|pastoral": "How might we surface pastoral notes in the right places for staff so that they can act with sensitivity and awareness when taking registers or covering lessons?",
  "Attendance & Registers|Staff absence and cover|cover-split": "How might we make splitting and adjusting cover simple for cover managers so that they can respond quickly when staff availability changes mid‑day?",
  "Attendance & Registers|Staff absence and cover|annual-leave": "How might we help admins manage annual leave and holidays for support staff so that they can see entitlements and clashes without maintaining separate trackers?",
  "Attendance & Registers|Roll call and daily settings|lunch-kitchen": "How might we give kitchen staff a clear daily view of lunch numbers so that they can plan portions confidently and reduce waste?",
  "Attendance & Registers|Roll call and daily settings|notes-pupils": "How might we make individual pupil notes easy to see during roll call so that teachers can respond to medical, pastoral, or safeguarding needs in the moment?",
  "Attendance & Registers|Notifications and acknowledgements|sibling": "How might we let attendance teams handle sibling or household absences together so that they can record one decision once instead of repeating work for each child?",
  "Attendance & Registers|Notifications and acknowledgements|alerts": "How might we design absence notifications for parents so that they clearly understand when a child is missing and what action they need to take?",
  "Attendance & Registers|Notifications and acknowledgements|notes-wipe": "How might we make the relationship between notes and marks clear for teachers so that they can change registers without accidentally wiping important context?",
  "Behaviour Management|Behaviour incidents and logging|changelog": "How might we provide a clear behaviour changelog for school leaders so that they can see who edited an incident and why, building trust in the data?",
  "Behaviour Management|Behaviour incidents and logging|student-visibility": "How might we give students appropriate visibility of their achievements and incidents so that they can understand the story behind their behaviour points and take ownership of change?",
  "Behaviour Management|Behaviour incidents and logging|mandatory": "How might we make behaviour narratives feel lightweight for teachers so that they can capture meaningful context without it becoming a blocker to logging incidents?",
  "Behaviour Management|Behaviour incidents and logging|incidents-logging": "How might we simplify behaviour logging flows for classroom staff so that they can record incidents accurately in the moment without losing control of the lesson?",
  "Behaviour Management|Detentions|session-blocking": "How might we make allocating pupils to detention sessions flexible for behaviour teams so that they can find slots that work without battling conflicting rules?",
  "Behaviour Management|Detentions|session-visibility": "How might we give staff a forward view of detentions so that they can quickly see who is due to attend and avoid clashes with other commitments?",
  "Behaviour Management|Detentions|student-copy": "How might we ensure students and parents consistently receive clear detention information so that there are fewer surprises and missed consequences?",
  "Behaviour Management|Detentions|detention-workflow": "How might we design detention workflows for heads of year so that setting up, running, and following up sessions feels like one joined‑up process?",
  "Behaviour Management|Points and rewards|student-view": "How might we present points and rewards to students so that they feel motivating, fair, and easy to understand in class and at home?",
  "Behaviour Management|Points and rewards|bulk-upload": "How might we let teachers award or adjust points in bulk so that they can celebrate or address whole groups without repetitive clicking?",
  "Behaviour Management|Points and rewards|narrative": "How might we encourage teachers to add short, meaningful narratives to behaviour points so that pupils and parents understand the reasons behind them?",
  "Behaviour Management|Points and rewards|achievement": "How might we spotlight positive behaviour for students so that teachers can easily recognise achievements and build a culture of praise, not just sanctions?",
  "Behaviour Management|Report cards and pastoral|progress-timeline": "How might we show progress over time on report cards for parents so that they can see improvements and concerns across a term, not just a single snapshot?",
  "Behaviour Management|Report cards and pastoral|notes-comm": "How might we bring key pastoral notes into communications views for staff so that letters and emails reflect the full context of a pupil’s situation?",
  "Behaviour Management|Report cards and pastoral|on-report": "How might we structure on‑report monitoring for behaviour teams so that they can track interventions consistently and know when to escalate or step back?",
  "Behaviour Management|Report cards and pastoral|layout": "How might we offer flexible report layouts for schools so that they can communicate progress in a format that feels professional and easy for families to read?",
  "Behaviour Management|Alerts and notifications|tagging": "How might we make tagging staff in behaviour events intuitive so that the right people are looped in without noisy, irrelevant alerts?",
  "Behaviour Management|Alerts and notifications|student-notif": "How might we design behaviour notifications for students so that they are timely, understandable, and encourage reflection rather than just punishment?",
  "Behaviour Management|Alerts and notifications|cover-email": "How might we streamline default email options around cover so that staff receive the updates they need without being overwhelmed by automated messages?",
  "Behaviour Management|Alerts and notifications|suspension": "How might we support schools in communicating suspensions so that guardians receive clear, sensitive information and understand next steps?",
  "Behaviour Management|Custom reports|filter-share": "How might we make custom behaviour reports easy to filter and share so that leaders can quickly answer questions from governors, trust boards, or inspectors?",
  "Behaviour Management|Custom reports|suspension-stats": "How might we help schools explore suspension statistics so that they can see trends by group and act early on disproportionate patterns?",
  "Behaviour Management|Custom reports|demographics": "How might we layer demographic information into behaviour reporting so that inclusion leads can understand how different groups are experiencing school?",
  "Behaviour Management|Permissions and visibility|reg-date": "How might we tidy up historic registration and cohort information so that staff always see accurate, up‑to‑date groupings for current pupils?",
  "Behaviour Management|Permissions and visibility|split-pos-neg": "How might we separate and visualise positive and negative behaviour for leaders so that they can see whether the culture is trending towards recognition or sanction?",
  "Behaviour Management|Permissions and visibility|teacher-name": "How might we ensure students and parents always see the correct teacher names on timetables so that they know who is responsible for each lesson?",
  "Behaviour Management|Physical intervention and safeguarding|record-pi": "How might we make recording physical interventions safe and structured for safeguarding leads so that they can meet legal requirements and review incidents with confidence?",
  "Behaviour Management|Physical intervention and safeguarding|limit-access": "How might we tightly control access to sensitive behaviour and safeguarding records so that only the right staff can see them while everyone else still has what they need to teach?",
  "Classroom Management|Seating plans and My Classroom|redundant": "How might we help teachers manage and tidy old seating layouts so that they can quickly switch between the arrangements that matter today without clutter?",
  "Classroom Management|Seating plans and My Classroom|customisation": "How might we let teachers personalise seating plans so that they can highlight key information and make layouts that genuinely support how they teach?",
  "Classroom Management|Seating plans and My Classroom|data-on-layout": "How might we bring rich student data onto seating plans so that teachers can see additional needs, support flags, and key indicators in the context of the room?",
  "Classroom Management|Seating plans and My Classroom|autonomy": "How might we give schools control over what appears on classroom layouts so that they can balance teacher autonomy with safeguarding and data‑sharing needs?",
  "Classroom Management|Seating plans and My Classroom|seating-my-classroom": "How might we make seating plans and My Classroom feel like a single, intuitive workspace for teachers so that they can move students around without losing track of who is where?",
  "Classroom Management|Room changes and timetable|cover-visibility": "How might we highlight cover on timetables so that teachers and students can instantly see when someone different is teaching a lesson?",
  "Classroom Management|Room changes and timetable|room-swaps": "How might we simplify room swaps for timetablers so that last‑minute changes are easy to make and clearly communicated to staff and students?",
  "Classroom Management|Room changes and timetable|crw-timetable": "How might we expose the right timetable fields in custom reports so that data leads can answer detailed questions about who was where and when?",
  "Classroom Management|Room changes and timetable|localisation": "How might we localise timetable views for schools so that days, labels, and language feel natural in their context?",
  "Classroom Management|Lesson dashboard and cover|context": "How might we enrich the lesson dashboard with key student context so that teachers can make better decisions during the lesson without leaving the page?",
  "Classroom Management|Lesson dashboard and cover|medical": "How might we make essential medical information visible yet discreet for teachers so that they can act quickly when needed without exposing private details unnecessarily?",
  "Classroom Management|Lesson dashboard and cover|lesson-cover": "How might we bring together lesson and cover information for teachers so that they always know who is teaching what and can pick up a class smoothly when covering?",
  "Classroom Management|Display and accessibility|bulk-day": "How might we offer whole‑day views and bulk editing tools for classroom staff so that they can manage attendance and notes across multiple lessons in one place?",
  "Classroom Management|Display and accessibility|attendance-subject": "How might we show attendance by subject for heads of department so that they can spot engagement issues in their area early?",
  "Classroom Management|Display and accessibility|parent-app": "How might we align the parent app and portal views so that families have a single, consistent picture of lessons, teachers, and attendance?",
  "Classroom Management|Display and accessibility|display-accessibility": "How might we design classroom and attendance views with accessibility in mind so that all staff, including those with visual needs, can use them comfortably?",
  "Classroom Management|Exam seating|register": "How might we connect exam seating and registers so that exams officers can be confident who attended which paper without maintaining duplicate lists?",
  "Classroom Management|Interventions and sessions|reports": "How might we improve intervention attendance reporting so that SENCOs and pastoral leads can see which support sessions are actually reaching the pupils who need them most?",
};

export function hmwKey(category: string, subCategory: string, themeId: string): string {
  return `${category}|${subCategory}|${themeId}`;
}

export function getHmw(category: string, subCategory: string, themeId: string): string | undefined {
  return HMW_STATEMENTS[hmwKey(category, subCategory, themeId)];
}
