/**
 * NPS-derived How Might We statements (from Teacher NPS 2025 feedback categories).
 * Key format: "category|subCategory|themeId". Generated by: npm run generate-nps-hmw
 * Curated for unique, outcome-focused HMWs per theme.
 */

export type HmwStatementsMap = Record<string, string>;

export const HMW_STATEMENTS_NPS: HmwStatementsMap = {
  "Behaviour Management|Behaviour incidents and logging|student-visibility": "How might we make behaviour and achievement information visible to students in the right place so that they can understand their own record and take ownership of their behaviour?",
  "Attendance & Registers|Clubs and wrap-around|reporting": "How might we simplify club and wrap-around reporting for office and club coordinators so that they can see session and attendance at a glance without manual spreadsheets?",
  "Attendance & Registers|Reporting and statistics|meal": "How might we connect attendance and meal choices for kitchen and office staff so that they can get accurate dinner numbers without chasing or double-entry?",
  "Attendance & Registers|Pre-planned absence and notes|notes-flow": "How might we ensure pre-planned absence notes flow into the register for teachers so that they can see the reason a pupil is away at the moment of taking the register?",
  "Attendance & Registers|Bulk edit and workflow|friction": "How might we streamline bulk attendance editing for attendance officers so that they can apply changes to whole cohorts in a few intuitive steps?",
  "Attendance & Registers|Evacuation and emergency registers|format": "How might we offer flexible evacuation list formats and filters for school leaders so that they can print or export the right view for their on-site procedures?",
  "Classroom Management|Seating plans and My Classroom|customisation": "How might we let teachers personalise seating plan display and notes so that they can highlight what matters for their lesson without cluttering the view?",
  "Attendance & Registers|Clubs and wrap-around|capacity": "How might we make club capacity and booking clearer for office staff and parents so that they can see availability and secure places without confusion?",
  "Attendance & Registers|Evacuation and emergency registers|display": "How might we improve how evacuation registers display and print for staff so that they can read them quickly in an emergency, including for visually impaired users?",
  "Attendance & Registers|Codes and marks|custom-census": "How might we simplify custom code and census mapping for attendance officers so that they can maintain school-specific codes without wrestling with the system?",
  "Attendance & Registers|Pre-planned absence and notes|overridden": "How might we protect pre-set absence marks from being accidentally overridden so that teachers and office staff can trust what was planned stays in place when the register is taken?",
  "Behaviour Management|Behaviour incidents and logging|incidents-logging": "How might we simplify logging and reviewing behaviour incidents for teachers and pastoral staff so that they can record what happened without losing teaching time?",
  "Classroom Management|Seating plans and My Classroom|data-on-layout": "How might we surface key pupil data (e.g. additional needs, UDFs) on seating plans for teachers so that they can arrange and support the class without opening multiple tabs?",
  "Behaviour Management|Alerts and notifications|student-notif": "How might we give students timely, clear notifications when behaviour points are recorded so that they and their families can see what was logged and why?",
  "Attendance & Registers|Bulk edit and workflow|latecomer": "How might we make latecomer and N/O code workflows clearer for attendance and house teams so that they can monitor and follow up without missing pupils?",
  "Attendance & Registers|Evacuation and emergency registers|access": "How might we put evacuation registers one tap away for staff so that they can open the right list quickly in an emergency?",
  "Attendance & Registers|Codes and marks|locking": "How might we clarify who can lock registers and change marks for attendance officers so that they can close the register confidently without permission surprises?",
  "Behaviour Management|Points and rewards|student-view": "How might we make points and rewards visible to students in the right context (e.g. on the board or in their view) so that they can see their progress and stay motivated?",
  "Behaviour Management|Points and rewards|achievement": "How might we make giving and viewing achievement points quick and visible for teachers so that they can celebrate positive behaviour without extra admin?",
  "Behaviour Management|Custom reports|demographics": "How might we layer demographic context into behaviour reports for inclusion and pastoral leads so that they can see how different groups are faring and target support?",
  "Classroom Management|Display and accessibility|display-accessibility": "How might we improve how classroom and register information is displayed for teachers so that they can scan and act quickly during live lessons?",
  "Behaviour Management|Detentions|detention-workflow": "How might we streamline setting and managing detentions for teachers and pastoral staff so that consequences are applied consistently without detentions slipping through the cracks?",
  "Behaviour Management|Physical intervention and safeguarding|record-pi": "How might we support clear, compliant recording of physical intervention for staff so that they can meet safeguarding and legislation requirements without ambiguity?",
  "Behaviour Management|Alerts and notifications|tagging": "How might we make it obvious who gets notified when behaviour is logged so that the right staff (e.g. class teacher, HOY) see alerts without overload or missed notifications?",
  "Behaviour Management|Permissions and visibility|teacher-name": "How might we control what teacher and staff names students see on timetables so that schools can balance clarity with privacy and safety?",
  "Attendance & Registers|Staff absence and cover|cover-split": "How might we simplify splitting and amending cover (e.g. double lessons) for cover coordinators so that they can assign cover accurately without manual workarounds?",
  "Behaviour Management|Report cards and pastoral|on-report": "How might we make on-report and structured monitoring easier to set up and track for pastoral leads so that they can intervene early and review progress in one place?",
  "Behaviour Management|Detentions|session-blocking": "How might we make assigning pupils to detention sessions (and fixing mistakes) straightforward for staff so that no-one is left unassigned or double-booked?",
  "Behaviour Management|Report cards and pastoral|notes-comm": "How might we surface pastoral and behaviour notes where staff send communications so that they can reference the full picture when contacting families?",
  "Attendance & Registers|Notifications and acknowledgements|alerts": "How might we deliver absence alerts to the right people at the right time so that staff and parents can respond quickly without notification fatigue?",
  "Attendance & Registers|Clubs and wrap-around|cancel": "How might we make cancelling club sessions and notifying families simple for staff so that last-minute changes don't leave parents or pupils in the dark?",
  "Attendance & Registers|Pre-planned absence and notes|ad-hoc": "How might we make it easy to record in-school interventions and ad hoc sessions as non-absence for office and attendance staff so that registers reflect reality without skewing absence stats?",
  "Behaviour Management|Points and rewards|bulk-upload": "How might we support bulk awarding of points or rewards for teachers so that they can recognise a whole class or group without entering each pupil individually?",
  "Behaviour Management|Behaviour incidents and logging|changelog": "How might we make behaviour changelogs and audit trails clear for pastoral and senior staff so that they can see who changed what and when when they need to?",
  "Behaviour Management|Detentions|session-visibility": "How might we show detention sessions far enough ahead for staff and students so that everyone can plan and no detention is missed because it was off the radar?",
  "Attendance & Registers|Roll call and daily settings|notes-pupils": "How might we put notes for individual pupils where teachers and pastoral staff need them (e.g. on the register or lesson view) so that they can act on context without hunting?",
  "Classroom Management|Seating plans and My Classroom|redundant": "How might we let teachers remove or archive redundant seating layouts without accidentally losing the wrong one so that their list stays manageable and clear?",
  "Behaviour Management|Detentions|student-copy": "How might we ensure students and parents receive a clear copy of detention details (reason, date, time) so that there are fewer surprises and fewer I didn't know conversations?",
  "Attendance & Registers|Staff absence and cover|annual-leave": "How might we make annual leave and 52-week contract handling clearer for office and HR so that support staff leave is recorded correctly and cover is planned with the right assumptions?",
  "Attendance & Registers|Pre-planned absence and notes|fines": "How might we surface unauthorised absence rules and fine thresholds clearly for attendance officers so that they can apply policy consistently and explain it to families?",
  "Classroom Management|Exam seating|register": "How might we align exam seating and register-taking for exams so that invigilators and office staff can confirm who was present without duplicate processes?",
  "Attendance & Registers|Bulk edit and workflow|peripatetic": "How might we support peripatetic and external staff (and paper or hybrid registers) for attendance and office teams so that their marks and presence count without workarounds?",
  "Classroom Management|Seating plans and My Classroom|seating-my-classroom": "How might we make seating plans and My Classroom work together smoothly for teachers so that they can set up the room and take the register in one familiar place?",
  "Classroom Management|Room changes and timetable|crw-timetable": "How might we make CRW and custom timetable fields reliable and easy to use for office and curriculum staff so that they can report and plan without data mismatches?",
};

export function getNpsHmw(category: string, subCategory: string, themeId: string): string | undefined {
  return HMW_STATEMENTS_NPS[`${category}|${subCategory}|${themeId}`];
}
