import type { ChangelogEntry } from "./types";

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  {
    id: "1",
    date: "2026-03-03",
    time: "09:00",
    category: "Project decision",
    title: "Removed school phase from product",
    body: "Phase checkboxes and all phase filtering removed from the Jira Feedback Dashboard. Product is no longer phase-scoped.",
  },
  {
    id: "2",
    date: "2026-03-03",
    time: "09:15",
    category: "Project decision",
    title: "Category and sub-category behaviour with “All”",
    body: "With “All categories” selected, the sub-category chart shows all data and the sub-category dropdown lists all sub-categories and stays enabled.",
  },
  {
    id: "3",
    date: "2026-03-03",
    time: "09:30",
    category: "Project decision",
    title: "Category quotes page",
    body: "New page (tiles view): feedback as comment-only tiles, copy (comment + ticket number) with “Copied!” confirmation, click opens ticket modal. “View evidence” from Product problems deep-links here with category/sub in URL.",
  },
  {
    id: "4",
    date: "2026-03-03",
    time: "09:45",
    category: "Project decision",
    title: "Product problems page scope",
    body: "Table with expandable rows (sub-category → theme), card counts, theme counts from keyword matching. No “Value to customer” column or “Sort by”; “View evidence” is a Base Web tertiary button linking to Category quotes.",
  },
  {
    id: "5",
    date: "2026-03-03",
    time: "10:00",
    category: "Build / technical",
    title: "Next.js and dependencies restored",
    body: "Restored full package.json: next, react, react-dom, baseui, styletron-engine-monolithic, styletron-react, recharts. Added tsconfig.json with baseUrl and paths for @/*.",
  },
  {
    id: "6",
    date: "2026-03-03",
    time: "10:15",
    category: "Build / technical",
    title: "CSS on custom port (3001)",
    body: "Added next.config.js with assetPrefix in development when PORT is set. Dev script set to PORT=3001 next dev so CSS and assets load correctly on http://localhost:3001.",
  },
  {
    id: "7",
    date: "2026-03-03",
    time: "10:30",
    category: "UI / design",
    title: "Form field styling",
    body: "Shared form field styles (white background, light grey border, hover) and BaseUI Select overrides in FormField.tsx; applied to category/sub-category dropdowns and Ask section.",
  },
  {
    id: "8",
    date: "2026-03-03",
    time: "10:45",
    category: "UI / design",
    title: "Sidebar grouping and Lucide icons",
    body: "Collapsible “Product Feedback” group in sidebar; Lucide icons (replacing emojis/carets) across sidebar, TopBar, HomePage, ProblemsView.",
  },
  {
    id: "9",
    date: "2026-03-03",
    time: "11:00",
    category: "UI / design",
    title: "Context Synthesis source lines removed",
    body: "Removed the “From research & Jira feedback” / “From User Experience framing” / “From Product & GTM alignment” lines from the homepage Context Synthesis cards.",
  },
  {
    id: "10",
    date: "2026-03-03",
    time: "11:15",
    category: "UI / design",
    title: "Layout and error handling",
    body: "globals.css and AppShell adjustments for height/scroll; ErrorBoundary in root layout to show a message instead of a blank screen on errors.",
  },
  {
    id: "11",
    date: "2026-03-03",
    time: "11:30",
    category: "Data / content",
    title: "Problem themes and keyword assignment",
    body: "Themes defined in problemThemes.ts with keywords; feedback assigned to themes by keyword match; broader keywords and more themes to reduce “Other”.",
  },
  {
    id: "12",
    date: "2026-03-03",
    time: "11:45",
    category: "Bug fix",
    title: "View evidence and BaseUI Button",
    body: "\"View evidence\" uses router.push() instead of Button as Link; fixed BaseUI Button import (named export from baseui/button).",
  },
  {
    id: "13",
    date: "2026-03-03",
    time: "12:00",
    category: "Bug fix",
    title: "Feedback list and filters",
    body: "TicketList key derived from category and subCategory so the list remounts and updates when filters change. CategoriesView: guard for searchParams possibly null.",
  },
  {
    id: "14",
    date: "2026-03-03",
    time: "12:15",
    category: "Bug fix",
    title: "Data loading and BaseUI theme",
    body: "Fetch handlers ensure data is always an array (Array.isArray check, [] on error). Dashboard, CategoriesView, ProblemsView wait for theme (useThemeReady) before rendering BaseUI. Providers: createLightTheme single-arg; ThemeReady context.",
  },
  {
    id: "15",
    date: "2026-03-03",
    time: "12:30",
    category: "Bug fix",
    title: "Sidebar nav icons",
    body: "Child nav items render icon via const Icon = item.Icon; return <Icon /> so the dynamic component is a valid React element.",
  },
  {
    id: "16",
    date: "2026-03-03",
    time: "12:45",
    category: "UI / design",
    title: "Changelog page and sidebar link",
    body: "New Changelog route (/changelog) with types (ChangelogCategory, ChangelogEntry), categories (Project decision, Build / technical, UI / design, Data / content, Bug fix), and 15 entries. Sidebar nav item “Changelog” with History icon added.",
  },
  {
    id: "17",
    date: "2026-03-03",
    time: "13:00",
    category: "UI / design",
    title: "Changelog category and sort filters",
    body: "Changelog page: Category dropdown (All + five categories) and Sort dropdown (Newest first / Oldest first). useMemo filters and sorts list; copy-before-sort to avoid mutating array.",
  },
  {
    id: "18",
    date: "2026-03-03",
    time: "13:15",
    category: "Bug fix",
    title: "Changelog filtering and sort behaviour",
    body: "Category filter: use e.currentTarget.value in onChange and trim() on category comparison. Sort: use date+time sort key (sortKey(entry)) so order changes when all dates are equal; time field optional on ChangelogEntry.",
  },
  {
    id: "19",
    date: "2026-03-03",
    time: "13:30",
    category: "Data / content",
    title: "Changelog time on entries and cards",
    body: "Added time (HH:mm) to all 15 changelog entries (09:00–12:30). Cards show formatDateTime(date, time); sort uses date+time so “Newest first” / “Oldest first” visibly reorders list.",
  },
  {
    id: "20",
    date: "2026-03-03",
    time: "09:05",
    category: "Project decision",
    title: "Phase state and filter UI removed",
    body: "Dashboard: removed phase from component state, filter UI, and any phase-based filtering so the product is no longer phase-scoped.",
  },
  {
    id: "21",
    date: "2026-03-03",
    time: "10:02",
    category: "Build / technical",
    title: "tsconfig path alias @/*",
    body: "Added tsconfig.json with baseUrl \".\" and paths {\"@/*\": [\"./*\"]} so imports like @/components/AppShell resolve correctly.",
  },
  {
    id: "22",
    date: "2026-03-03",
    time: "10:08",
    category: "Build / technical",
    title: "recharts and baseui/styletron versions",
    body: "Added recharts for PhaseJourneyCharts. Set styletron-engine-monolithic ^1.0.0 and styletron-react ^6.1.1 (npm-available versions); baseui ^14.0.0.",
  },
  {
    id: "23",
    date: "2026-03-03",
    time: "11:18",
    category: "Bug fix",
    title: "createLightTheme single argument",
    body: "BaseUI createLightTheme in providers.tsx called with one argument (primaryFontFamily) only; second empty object removed to fix type error.",
  },
  {
    id: "24",
    date: "2026-03-03",
    time: "11:20",
    category: "Bug fix",
    title: "ThemeReady context for BaseUI",
    body: "Providers export ThemeReadyContext and useThemeReady(). Dashboard, CategoriesView, ProblemsView show loading until themeReady so BaseUI Select/Heading mount after BaseProvider.",
  },
  {
    id: "25",
    date: "2026-03-03",
    time: "11:12",
    category: "UI / design",
    title: "ErrorBoundary in root layout",
    body: "New ErrorBoundary component catches render errors and shows “Something went wrong” plus Try again; root layout wraps AppShell in ErrorBoundary.",
  },
  {
    id: "26",
    date: "2026-03-03",
    time: "10:12",
    category: "Build / technical",
    title: "next.config.js and PORT=3001 dev script",
    body: "next.config.js sets assetPrefix to http://localhost:${PORT} in development when PORT is set. package.json dev script: PORT=3001 next dev so CSS and assets load on port 3001.",
  },
  {
    id: "27",
    date: "2026-03-03",
    time: "12:02",
    category: "Bug fix",
    title: "TicketList key from filters",
    body: "Dashboard TicketList key set to `${category ?? 'all'}-${subCategory ?? 'all'}` so the list remounts and updates when category or sub-category changes.",
  },
  {
    id: "28",
    date: "2026-03-03",
    time: "12:04",
    category: "Bug fix",
    title: "Defensive data loading",
    body: "Dashboard, CategoriesView, ProblemsView: fetch sets data to Array.isArray(json) ? json : [] and [] on catch so .map/.filter never run on non-array.",
  },
];
