/**
 * Generates NPS-derived HMW statements (HMW writing expert formula).
 * Run: npm run generate-nps-hmw
 * Reads public/nps_feedback_2025.json, writes app/npsHmwStatements.ts
 */
const fs = require("fs");
const path = require("path");

const dir = path.join(__dirname, "..");
const npsPath = path.join(dir, "public", "nps_feedback_2025.json");
const outPath = path.join(dir, "app", "npsHmwStatements.ts");

const nps = JSON.parse(fs.readFileSync(npsPath, "utf8"));
const seen = new Set();
const keys = [];
for (const row of nps) {
  const cat = row["top_level_category"] || "";
  const sub = row["sub_category"] || "";
  const theme = row["theme_id"] || "";
  if (cat === "Uncategorised" || sub === "Uncategorised" || theme === "other") continue;
  const key = `${cat}|${sub}|${theme}`;
  if (seen.has(key)) continue;
  seen.add(key);
  keys.push({ category: cat, subCategory: sub, themeId: theme });
}

function labelFromId(id) {
  return id
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}
function userFor(c) {
  if (c === "Attendance & Registers") return "attendance staff and office teams";
  if (c === "Behaviour Management") return "teachers and behaviour teams";
  if (c === "Classroom Management") return "classroom teachers and staff";
  return "teachers and school staff";
}
const verbs = [
  "improve",
  "simplify",
  "surface",
  "make it easier to manage",
  "support",
  "streamline",
  "clarify",
  "strengthen",
];
const outcomes = {
  "Attendance & Registers":
    "spend less time on admin and more time supporting pupils and staff",
  "Behaviour Management":
    "focus on teaching and pastoral support instead of fighting the system",
  "Classroom Management":
    "teach and take registers with confidence and minimal friction",
};

const statements = {};
let idx = 0;
for (const { category, subCategory, themeId } of keys) {
  const label = labelFromId(themeId);
  const user = userFor(category);
  const verb = verbs[idx % verbs.length];
  const outcome =
    outcomes[category] ||
    "get the most from this part of the system without extra friction";
  const hmw = `How might we ${verb} ${label.toLowerCase()} for ${user} so that they can ${outcome}?`;
  statements[`${category}|${subCategory}|${themeId}`] = hmw;
  idx++;
}

function esc(s) {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
}
const lines = [
  "/**",
  " * NPS-derived How Might We statements (from Teacher NPS 2025 feedback categories).",
  ' * Key format: "category|subCategory|themeId". Generated by: npm run generate-nps-hmw',
  " */",
  "",
  "export type HmwStatementsMap = Record<string, string>;",
  "",
  "export const HMW_STATEMENTS_NPS: HmwStatementsMap = {",
  ...Object.entries(statements).map(
    ([k, v]) => `  "${esc(k)}": "${esc(v)}",`
  ),
  "};",
  "",
  "export function getNpsHmw(category: string, subCategory: string, themeId: string): string | undefined {",
  "  return HMW_STATEMENTS_NPS[`" + "${category}|${subCategory}|${themeId}" + "`];",
  "}",
];
fs.writeFileSync(outPath, lines.join("\n") + "\n");
console.log("Wrote", Object.keys(statements).length, "NPS HMW statements to app/npsHmwStatements.ts");
