/**
 * One-off script to generate How Might We (HMW) statements for all themes
 * (excluding "other") using OpenAI. Run from dashboard/: npm run generate-hmw
 * Requires OPENAI_API_KEY in .env.local or environment.
 */

import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";

// Load .env.local from project root (dashboard/)
dotenv.config({ path: path.join(__dirname, "../.env.local") });

const PROBLEM_THEMES = require("../app/problemThemes").PROBLEM_THEMES as Record<
  string,
  Array<{ id: string; label: string; description?: string; keywords: string[] }>
>;

const HMW_FILE = path.join(__dirname, "../app/hmwStatements.ts");

const HMW_SYSTEM = `You are a product designer with world‑class craft (think Apple, OpenAI, Cursor, Spotify, Airbnb). Given a feedback theme (label and description from teacher/school feedback), write exactly one "How Might We" (HMW) statement for design discussions.
Required structure (in order): "How might we" + [Action] + [User] + [Desired Outcome].
Concretely, your sentence MUST look like:
  "How might we [do what/change what] for [which teachers or staff] so that they can [clear, specific benefit]?"

Very important:
- The text after "so that" MUST start with "they can" (or "they are able to") and describe a concrete, positive capability or outcome.
- Do NOT restate the problem after "so that". Avoid words like "issues", "problems", "friction", "complaints", "feedback about", etc.
- VARY the benefits and phrasing across themes. Do NOT repeat generic phrases like "work more efficiently and confidently" for multiple themes.
- Prefer vivid, outcome‑focused language, e.g. "quickly update registers in a few clicks", "spot at‑risk students early", "trust that notes are always in the right place".

Rules:
- One sentence only.
- Start with "How might we".
- Include both the action and the specific user group (e.g. "attendance officers", "classroom teachers", "office staff").
- No quotation marks or prefix in your reply.
- Be specific to the theme and avoid naming particular UI components or solutions.`;

async function generateHmw(label: string, description: string): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    // Simple fallback when no API is available; still follow the structure roughly.
    return `How might we improve ${label.toLowerCase()} for teachers and school staff so that they can better handle ${description.toLowerCase()}?`;
  }
  const userContent = `Theme label: ${label}\nTheme description: ${description}`;
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: HMW_SYSTEM },
        { role: "user", content: userContent },
      ],
      max_tokens: 120,
      temperature: 0.3,
    }),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`OpenAI API error: ${err}`);
  }
  const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
  const text = json.choices?.[0]?.message?.content?.trim() ?? "";
  return text || `How might we improve ${label.toLowerCase()} for teachers and school staff so that they can better handle ${description.toLowerCase()}?`;
}

function escapeForTs(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

async function main() {
  const statements: Record<string, string> = {};
  const entries = Object.entries(PROBLEM_THEMES);
  let done = 0;
  for (const [mapKey, themes] of entries) {
    const [category, subCategory] = mapKey.split("|");
    for (const theme of themes) {
      if (theme.id === "other") continue;
      const key = `${category}|${subCategory}|${theme.id}`;
      process.stdout.write(`[${++done}] ${category} › ${theme.label}... `);
      try {
        const hmw = await generateHmw(theme.label, theme.description || theme.label);
        statements[key] = hmw;
        console.log("OK");
      } catch (e) {
        const fallback = `How might we improve ${theme.label.toLowerCase()} for teachers and school staff so that they can better handle ${
          (theme.description || "this part of the system").toLowerCase()
        }?`;
        statements[key] = fallback;
        console.log("Fallback:", (e as Error).message);
      }
      await new Promise((r) => setTimeout(r, 250));
    }
  }

  const lines: string[] = [
    `/**`,
    ` * How Might We (HMW) statements per theme for design discussions.`,
    ` * Key format: "category|subCategory|themeId".`,
    ` * Generated by: npm run generate-hmw`,
    ` */`,
    ``,
    `export type HmwStatementsMap = Record<string, string>;`,
    ``,
    `export const HMW_STATEMENTS: HmwStatementsMap = {`,
    ...Object.entries(statements).map(
      ([k, v]) => `  "${escapeForTs(k)}": "${escapeForTs(v)}",`
    ),
    `};`,
    ``,
    `export function hmwKey(category: string, subCategory: string, themeId: string): string {`,
    `  return \`\${category}|\${subCategory}|\${themeId}\`;`,
    `}`,
    ``,
    `export function getHmw(category: string, subCategory: string, themeId: string): string | undefined {`,
    `  return HMW_STATEMENTS[hmwKey(category, subCategory, themeId)];`,
    `}`,
  ];

  fs.writeFileSync(HMW_FILE, lines.join("\n") + "\n", "utf-8");
  console.log(`\nWrote ${Object.keys(statements).length} HMW statements to app/hmwStatements.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
